name: ikut3
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.2
  web_socket_channel: ^2.3.0
  uuid: ^3.0.7
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
