# ワークフローの名前
name: check
# ワークフロー実行タイミングは
on:
  # main ブランチへの PUSH
  push:
    branches:
      - main
  # プルリクの作成と更新
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check: # job 名
    # ubuntu で動かす
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # ソースコードのチェックアウト
      - uses: actions/checkout@v3
        with:
          # Codecov のために必要な設定
          fetch-depth: 0
      # Flutter 環境のセットアップ
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true
      # 依存ライブラリのダウンロード
      - run: flutter pub get
      # freezed のために build_runner の実行
      - run: flutter pub run build_runner build
      # フォーマットの確認
      - run: dart format --set-exit-if-changed .
      # lint チェック
      - run: flutter analyze
      # 単体テストの実行とカバレッジレポートの出力
      - run: flutter test --coverage
        # 日付処理のテストがあるので、ローカルタイムを日本にする
        env:
          TZ: Asia/Tokyo
      # カバレッジレポートを Codecov に送る
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
