# ワークフローの名前
name: release
# ワークフロー実行タイミングは
on:
  # release ブランチへの PUSH
  push:
    branches:
      - release
jobs:
  staging: # job 名
    # ubuntu で動かす
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Firebase CLI をインストールする
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g firebase-tools
      # checkout する
      - uses: actions/checkout@v3
      # Flutter 環境のセットアップ
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true
      # ビルドする
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build web
      # デプロイする
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting:release
